# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joy Never Ends...
tagline:          'A Jekyll theme'
description:      'Agile Practitioner'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Joy Ge'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
